=== MarcoRay85/InitFolder/VS/IntactVisionServer/NITPROGRAM.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema  attributeFormDefault="unqualified"
            elementFormDefault="qualified"
            xmlns:xs="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://imt.zeiss.de/neointacttest"
            xmlns:nit="http://imt.zeiss.de/neointacttest">
  <xs:simpleType name="EvacMode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="symmetric"/>
      <xs:enumeration value="unsymmetric"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="CycleType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="eNone"/>
      <xs:enumeration value="eStartPrep4Transport"/>
      <xs:enumeration value="eStartPrep4Measure"/>
      <xs:enumeration value="eMove"/>
      <xs:enumeration value="eMeasure"/>
      <xs:enumeration value="eDelay500ms"/>
      <xs:enumeration value="eDelay1s"/>
      <xs:enumeration value="eDelay2s"/>
      <xs:enumeration value="eDelay4s"/>
      <xs:enumeration value="eDelay8s"/>
      <xs:enumeration value="eDelay16s"/>
      <xs:enumeration value="eOpenDoors"/>
      <xs:enumeration value="eCloseDoors"/>
      <xs:enumeration value="eStartPump"/>
      <xs:enumeration value="eStopPump"/>
      <xs:enumeration value="eOnLasers"/>
      <xs:enumeration value="eOffLasers"/>
      <xs:enumeration value="eRemeasureTire"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="neointacttest">  
    <xs:complexType>
      <xs:sequence>
        <xs:element name="header">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string" />
              <xs:element name="created_at" type="xs:dateTime" />
              <xs:element name="changed_at" type="xs:dateTime" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="parameters">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="validation">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="tire">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="innerdiameter">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:float">
                                  <xs:attribute name="check" type="xs:boolean" use="required" />
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="outerdiameter">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:float">
                                  <xs:attribute name="check" type="xs:boolean" use="required" />
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="width">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:float">
                                  <xs:attribute name="check" type="xs:boolean" use="required" />
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="tolerance" type="xs:float" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="evacmode" type="nit:EvacMode" />
              <xs:element name="simulate_pressure" type="xs:boolean" />
              <xs:element name="pressure" type="xs:short" />
              <xs:element name="press_sim_duration" type="xs:time" />
              <xs:element name="flip" type="xs:boolean" />
              <xs:element name="delay_after_flip" type="xs:time" />
              <xs:element name="transport_back" type="xs:boolean" />
              <xs:element name="delay_after_transport_back" type="xs:time" />
              <xs:element name="delay_before_acquisition" type="xs:time" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="job">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="cycles">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="cycle">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="type" type="nit:CycleType"/>
                          <xs:element name="axes_groups">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element maxOccurs="unbounded" name="axes_group">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="destination" type="xs:float" />
                                    </xs:sequence>
                                    <xs:attribute name="index" type="xs:unsignedByte" use="required" />
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="index" type="xs:unsignedByte" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== MarcoRay85/InitFolder/VS/IntactVisionServer/TEST_PROGRAM.XML
<?xml version="1.0" encoding="UTF-8" ?>
<nit:neointacttest
   xmlns="https://www.w3schools.com"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xmlns:nit="http://imt.zeiss.de/neointacttest"
   xsi:schemaLocation="http://imt.zeiss.de/neointacttest NITPROGRAM.xsd">
	<nit:header>
		<nit:name>Parser test program</nit:name>
		<nit:created_at>2020-01-23T10:00:00</nit:created_at>
		<nit:changed_at>2020-01-23T10:00:00</nit:changed_at>
	</nit:header>	
	<nit:parameters>
		<nit:validation>
			<nit:tire>
				<nit:innerdiameter check="true">600</nit:innerdiameter>
				<nit:outerdiameter check="true">1080</nit:outerdiameter>
				<nit:width check="false">270</nit:width>
				<nit:tolerance>50</nit:tolerance>
			</nit:tire>
		</nit:validation>
		<nit:evacmode>symmetric</nit:evacmode>
    <nit:simulate_pressure>false</nit:simulate_pressure>
		<nit:pressure>25</nit:pressure>
    <nit:press_sim_duration>00:00:03</nit:press_sim_duration>
		<nit:flip>true</nit:flip>
		<nit:delay_after_flip>00:00:05</nit:delay_after_flip>
		<nit:transport_back>true</nit:transport_back>
		<nit:delay_after_transport_back>00:00:10</nit:delay_after_transport_back>
    <nit:delay_before_acquisition>00:00:02</nit:delay_before_acquisition>
	</nit:parameters>
	<nit:job>
		<nit:cycles>
			<nit:cycle index="1">
				<nit:type>eStartPrep4Measure</nit:type>
				<nit:axes_groups>
					<nit:axes_group index="1">
						<nit:destination>NaN</nit:destination>
					</nit:axes_group>
					<nit:axes_group index="2">
						<nit:destination>NaN</nit:destination>
					</nit:axes_group>
					<nit:axes_group index="3">
						<nit:destination>NaN</nit:destination>
					</nit:axes_group>
					<nit:axes_group index="4">
						<nit:destination>NaN</nit:destination>
					</nit:axes_group>
				</nit:axes_groups>
			</nit:cycle>
			<nit:cycle index="2">
				<nit:type>eMove</nit:type>
				<nit:axes_groups>
					<nit:axes_group index="1">
						<nit:destination>590.0</nit:destination>
					</nit:axes_group>
					<nit:axes_group index="2">
						<nit:destination>235</nit:destination>
					</nit:axes_group>
					<nit:axes_group index="3">
						<nit:destination>510.0</nit:destination>
					</nit:axes_group>
					<nit:axes_group index="4">
						<nit:destination>212.0</nit:destination>
					</nit:axes_group>
				</nit:axes_groups>
			</nit:cycle>
			<nit:cycle index="3">
				<nit:type>eMeasure</nit:type>
				<nit:axes_groups>
					<nit:axes_group index="1">
						<nit:destination>NaN</nit:destination>
					</nit:axes_group>
					<nit:axes_group index="2">
						<nit:destination>NaN</nit:destination>
					</nit:axes_group>
					<nit:axes_group index="3">
						<nit:destination>NaN</nit:destination>
					</nit:axes_group>
					<nit:axes_group index="4">
						<nit:destination>NaN</nit:destination>
					</nit:axes_group>
				</nit:axes_groups>
			</nit:cycle>
			<nit:cycle index="4">
				<nit:type>eStartPrep4Transport</nit:type>
				<nit:axes_groups>
					<nit:axes_group index="1">
						<nit:destination>NaN</nit:destination>
					</nit:axes_group>
					<nit:axes_group index="2">
						<nit:destination>NaN</nit:destination>
					</nit:axes_group>
					<nit:axes_group index="3">
						<nit:destination>NaN</nit:destination>
					</nit:axes_group>
					<nit:axes_group index="4">
						<nit:destination>NaN</nit:destination>
					</nit:axes_group>
				</nit:axes_groups>
			</nit:cycle>
			<nit:cycle index="5">
            <nit:type>eMove</nit:type>
				<nit:axes_groups>
					<nit:axes_group index="1">
						<nit:destination>798.0</nit:destination>
					</nit:axes_group>
					<nit:axes_group index="2">
						<nit:destination>747.0</nit:destination>
					</nit:axes_group>
					<nit:axes_group index="3">
						<nit:destination>520.5</nit:destination>
					</nit:axes_group>
					<nit:axes_group index="4">
						<nit:destination>86.5</nit:destination>
					</nit:axes_group>
				</nit:axes_groups>
			</nit:cycle>
		</nit:cycles>
	</nit:job>
</nit:neointacttest>
